# Generated by Django 5.2 on 2025-12-02 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('purpose', models.TextField(blank=True, help_text='Reason for tracking request')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('update_interval', models.IntegerField(default=30, help_text='Location update interval in seconds')),
                ('allow_ai_prediction', models.BooleanField(default=True)),
                ('allow_heatmap', models.BooleanField(default=True)),
                ('send_alerts', models.BooleanField(default=True)),
                ('safe_zones', models.JSONField(blank=True, default=list)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_requests', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Permission',
                'verbose_name_plural': 'Location Permissions',
                'db_table': 'location_permissions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('entry', 'Entered Safe Zone'), ('exit', 'Exited Safe Zone'), ('stop', 'Stopped Moving'), ('speed', 'Speeding Detected'), ('anomaly', 'Anomalous Behavior'), ('battery', 'Low Battery'), ('offline', 'Device Offline')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('location', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='permissions.locationpermission')),
            ],
            options={
                'verbose_name': 'Permission Alert',
                'verbose_name_plural': 'Permission Alerts',
                'db_table': 'permission_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafeZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.IntegerField(default=500, help_text='Radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('send_entry_alert', models.BooleanField(default=True)),
                ('send_exit_alert', models.BooleanField(default=True)),
                ('active_days', models.JSONField(default=list, help_text='Days when safe zone is active (0=Monday, 6=Sunday)')),
                ('active_start_time', models.TimeField(blank=True, null=True)),
                ('active_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safe Zone',
                'verbose_name_plural': 'Safe Zones',
                'db_table': 'safe_zones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='locationpermission',
            index=models.Index(fields=['requester', 'status'], name='location_pe_request_597ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpermission',
            index=models.Index(fields=['target', 'status'], name='location_pe_target__bcb9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpermission',
            index=models.Index(fields=['expires_at'], name='location_pe_expires_2a6470_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpermission',
            index=models.Index(fields=['is_active'], name='location_pe_is_acti_a89399_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationpermission',
            unique_together={('requester', 'target')},
        ),
        migrations.AddIndex(
            model_name='permissionalert',
            index=models.Index(fields=['permission', 'is_read'], name='permission__permiss_855ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionalert',
            index=models.Index(fields=['alert_type', 'severity'], name='permission__alert_t_b8f30b_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionalert',
            index=models.Index(fields=['created_at'], name='permission__created_abeecc_idx'),
        ),
        migrations.AddIndex(
            model_name='safezone',
            index=models.Index(fields=['user', 'is_active'], name='safe_zones_user_id_b595b0_idx'),
        ),
    ]
