# Generated by Django 5.2 on 2025-12-02 15:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(help_text='Accuracy in meters')),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('is_moving', models.BooleanField(default=True)),
                ('activity_type', models.CharField(blank=True, choices=[('stationary', 'Stationary'), ('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('driving', 'Driving')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Data',
                'verbose_name_plural': 'Location Data',
                'db_table': 'location_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='location_da_user_id_1445ce_idx'), models.Index(fields=['latitude', 'longitude'], name='location_da_latitud_eec5f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_distance', models.FloatField(default=0, help_text='Total distance in km')),
                ('avg_speed', models.FloatField(default=0, help_text='Average speed in km/h')),
                ('max_speed', models.FloatField(default=0, help_text='Max speed in km/h')),
                ('time_stationary', models.IntegerField(default=0, help_text='Minutes')),
                ('time_walking', models.IntegerField(default=0, help_text='Minutes')),
                ('time_driving', models.IntegerField(default=0, help_text='Minutes')),
                ('unique_locations', models.IntegerField(default=0)),
                ('frequent_locations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'db_table': 'location_history',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
